version: '3.0'

services:

  app:
    container_name: vktestgo
    build:
      context: .
    healthcheck:
      test: [ "CMD-SHELL", "curl -sS vktestgo:2024 || exit 1" ]
      interval: 3s
      timeout: 2s
      retries: 5
    ports:
      - 2024:2024
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    # command: "-c logging_collector=on && -c log_statement=all && -c log_min_error_statement=DEBUG1 && -c log_destination=stderr"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 3s
      retries: 5
    volumes:
      - ./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - pgdata:/var/lib/postgresql/data
  pgadm:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:5050"
      - "80:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
  pgadmin-data: